### ISSUE TITLE
Angled bracket completion not working

### ISSUE THREAD

**Issue by neet-h-patel** [AiryShift/spaces-inside-braces#2]
Hello! Thank you for the wonderful plugin, however, I am having issues with it
not inserting the closing angled bracket. The rest of them work fine.

**Comment by AiryShift** [comment]
VS Code actually doesn't automatically insert the closing angle bracket because in many languages `<` is used as a "less than" operator and thus creating `<>` when you type `<` isn't what you'd want. I agree that it's a bit clunky to type `<>` then move the cursor back to the middle _then_ press space but that's how it is. I could look into implementing the closing of the angle bracket if you'd like, but I don't think it'll happen properly until [this issue](https://github.com/Microsoft/vscode/issues/26707) is resolved, as automatic closing of the angle bracket is _not_ something you'd want by default in a language like Python for example.

**Comment by neet-h-patel** [comment]
I see. No problem!
